import Link from "next/link";
import { ArrowLeft, ShieldCheck } from "lucide-react";

export const metadata = {title:"Kebijakan Privasi — FinanceTrack",description:"Kebijakan privasi aplikasi FinanceTrack."};

export default function PrivacyPage(){return <main className="privacy-page"><article>
  <Link href="/"><ArrowLeft size={18}/>Kembali ke FinanceTrack</Link>
  <div className="privacy-title"><span><ShieldCheck/></span><div><p>Terakhir diperbarui: 30 September 2026</p><h1>Kebijakan Privasi FinanceTrack</h1></div></div>
  <p>Kebijakan ini menjelaskan data yang digunakan oleh FinanceTrack versi 1.6.0 pada web dan Android. FinanceTrack adalah aplikasi pencatatan keuangan pribadi yang dikembangkan oleh Yusuf.</p>
  <h2>Data lokal dan pilihan sinkronisasi</h2><p>FinanceTrack dapat digunakan tanpa akun. Transaksi, dompet, anggaran, tujuan, utang-piutang, tagihan, catatan, preferensi, PIN, dan foto struk diproses di perangkat. Data tersebut dikirim ke Firebase hanya jika Anda memilih masuk dengan Google dan menggunakan sinkronisasi. Sinkronisasi bersifat opsional dan aplikasi tetap dapat digunakan secara lokal tanpa login.</p>
  <h2>Akun Google dan Firebase</h2><p>Jika Anda memilih “Masuk dengan Google”, Google Sign-In dan Firebase Authentication memproses informasi akun seperti nama, alamat email, ID pengguna Firebase, serta informasi profil dasar yang disediakan Google. Data digunakan untuk autentikasi, pengelolaan akun, dan memisahkan data setiap pengguna. FinanceTrack tidak menerima atau menyimpan kata sandi Google Anda.</p>
  <h2>Informasi keuangan</h2><p>Data transaksi, pemasukan, pengeluaran, saldo dompet, anggaran, tujuan tabungan, utang-piutang, tagihan, kategori, tanggal, dan catatan yang Anda masukkan digunakan untuk menyediakan fungsi pencatatan serta laporan keuangan. Jika sinkronisasi diaktifkan, data tersebut disimpan di Cloud Firestore berdasarkan UID pengguna dan tidak dijual atau digunakan untuk periklanan.</p>
  <h2>Foto struk</h2><p>Saat Anda memilih foto struk, FinanceTrack membuka pemilih foto atau kamera perangkat. Hanya gambar yang Anda pilih yang diproses. Tanpa login, gambar disimpan bersama data lokal. Ketika akun Google dan sinkronisasi aktif, foto disimpan pada folder UID pengguna di Firebase Storage agar dapat dipulihkan pada perangkat lain.</p>
  <h2>Cadangan dan ekspor</h2><p>Anda dapat mengekspor cadangan JSON serta laporan PDF atau CSV. File dibuat setelah Anda memilih fitur tersebut dan disimpan atau dibagikan melalui pilihan sistem perangkat. FinanceTrack tidak mengunggah file ekspor tersebut secara otomatis.</p>
  <h2>Izin dan fitur perangkat</h2><p>FinanceTrack menggunakan internet untuk login dan sinkronisasi, notifikasi untuk pengingat yang Anda buat, serta autentikasi biometrik sistem jika diaktifkan. FinanceTrack tidak menerima atau menyimpan sidik jari maupun data wajah, serta tidak meminta akses kontak, lokasi, SMS, atau riwayat telepon.</p>
  <h2>Pembayaran Premium</h2><p>Jika Anda membeli Premium melalui Google Play, FinanceTrack mengirim ID produk, token pembelian, dan pengenal akun Firebase yang di-hash ke server verifikasi. Server memeriksa status pembayaran serta langganan melalui Google Play, lalu menyimpan hak akses Premium berdasarkan akun Firebase. Data ini digunakan untuk mengaktifkan, memulihkan, dan memperbarui hak akses, termasuk ketika langganan kedaluwarsa atau pembelian dibatalkan. Pembayaran diproses Google Play; FinanceTrack tidak menerima nomor kartu atau detail rekening pembayaran.</p><p>Menghapus akun atau aplikasi tidak membatalkan perpanjangan langganan. Batalkan langganan melalui Google Play terlebih dahulu. Saat akun dihapus, token pembelian serta kaitan UID dihapus dari catatan server. Hash token dan hash pengenal akun dipertahankan untuk mencegah klaim pembelian yang sama oleh akun lain. Penghapusan akun bersifat permanen; hak Premium terkait akun yang dihapus tidak dapat dipindahkan ke akun Firebase baru.</p>
  <h2>Diagnostik dan Crashlytics</h2><p>FinanceTrack versi ini belum menggunakan Firebase Crashlytics dan tidak mengumpulkan log kerusakan atau diagnostik melalui layanan tersebut. Jika Crashlytics diaktifkan pada versi berikutnya, kebijakan ini dan formulir Data Safety Google Play akan diperbarui untuk menjelaskan log kerusakan, diagnostik, serta pengenal instalasi yang diproses.</p>
  <h2>Keamanan dan enkripsi</h2><p>Data yang dikirim ke Google dan Firebase dilindungi menggunakan koneksi HTTPS/TLS saat transit. Akses Firestore dan Storage dibatasi berdasarkan UID melalui Firebase Security Rules. PIN disimpan sebagai nilai hash pada perangkat, sedangkan verifikasi biometrik dilakukan oleh sistem operasi.</p>
  <h2>Penyimpanan dan penghapusan</h2><p>Data lokal tersimpan sampai Anda menghapusnya dari Pengaturan, menghapus penyimpanan aplikasi, atau mencopot aplikasi. Pengguna akun Google dapat memilih “Hapus akun dan data” di Pengaturan untuk menghapus akun Firebase Authentication, dokumen Firestore, foto Firebase Storage, data sinkronisasi, keanggotaan keluarga, dan data lokal perangkat. Permintaan juga dapat diajukan melalui halaman <Link href="/delete-account">Penghapusan Akun</Link>.</p>
  <h2>Berbagi dan penjualan data</h2><p>FinanceTrack tidak menjual data pribadi, catatan keuangan, maupun foto pengguna. Google dan Firebase bertindak sebagai penyedia layanan untuk autentikasi, penyimpanan, dan sinkronisasi sesuai fungsi yang dipilih pengguna. FinanceTrack tidak membagikan data kepada pengiklan.</p>
  <h2>Anak-anak</h2><p>FinanceTrack ditujukan untuk pengguna umum dan tidak secara khusus ditujukan kepada anak-anak di bawah 13 tahun.</p>
  <h2>Kontak</h2><p>Untuk pertanyaan privasi atau penghapusan data, hubungi <a href="mailto:spywarecode97@gmail.com">spywarecode97@gmail.com</a>.</p>
</article></main>}
